package com.bfits.entityproviderdemo.entity;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * example entity
 *
 * @author FlassakD
 *
 */
@Entity
@Access(AccessType.FIELD)
public class Superhero {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull(message = "Super hero name is required.")
    @Column(length = 50, unique = true)
    @Size(min = 2, max = 50, message = "Super hero name must be 2 to 50 characters.")
    // @Pattern(regexp = "([A-Z][a-z]+[ -])*[A-Z][a-z]+", message = "Super hero name does not match regex: ([A-Z][a-z]+[ -])*[A-Z][a-z]+")
    private String superheroName;

    @NotNull
    @OneToOne
    private Person boringIdentity;

    /**
     * auto-generated by Eclipse with Id as only relevant field
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Superhero other = (Superhero) obj;
        if (id != other.id) {
            return false;
        }
        return true;
    }

    public Person getBoringIdentity() {
        return boringIdentity;
    }

    public Long getId() {
        return id;
    }

    public String getSuperheroName() {
        return superheroName;
    }

    /**
     * auto-generated by Eclipse with Id as only relevant field
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (id ^ (id >>> 32));
        return result;
    }

    public void setBoringIdentity(Person boringIdentity) {
        this.boringIdentity = boringIdentity;
    }

    public void setSuperheroName(String superheroName) {
        this.superheroName = superheroName;
    }

    @Override
    public String toString() {
        return superheroName;
    }

}
